name: flutter_application_1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^4.3.3
  flutter_bloc: ^6.0.0
  flutter_math: ^0.2.1
  flutter_conditional_rendering: ^1.1.1
  animated_button: ^0.1.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
#fonts:
#  - family: Montserrat
#fonts:
#  - assets: asset/Montserrat-Regular/ttf  
  assets:
   - assets/play_cards/7_s.png
   - assets/play_cards/8_s.png
   - assets/play_cards/9_s.png
   - assets/play_cards/10_s.png
   - assets/play_cards/J_s.png
   - assets/play_cards/K_s.png
   - assets/play_cards/Q_s.png
   - assets/play_cards/A_s.png
   - assets/play_cards/7_c.png
   - assets/play_cards/8_c.png
   - assets/play_cards/9_c.png
   - assets/play_cards/10_c.png
   - assets/play_cards/J_c.png
   - assets/play_cards/K_c.png
   - assets/play_cards/Q_c.png
   - assets/play_cards/A_c.png
   - assets/play_cards/7_d.png
   - assets/play_cards/8_d.png
   - assets/play_cards/9_d.png
   - assets/play_cards/10_d.png
   - assets/play_cards/J_d.png
   - assets/play_cards/K_d.png
   - assets/play_cards/Q_d.png
   - assets/play_cards/A_d.png
   - assets/play_cards/7_h.png
   - assets/play_cards/8_h.png
   - assets/play_cards/9_h.png
   - assets/play_cards/10_h.png
   - assets/play_cards/J_h.png
   - assets/play_cards/K_h.png
   - assets/play_cards/Q_h.png
   - assets/play_cards/A_h.png
   - assets/icecrown_card.png
   - assets/pika.png
   - assets/chirva.png
   - assets/trefa.png
   - assets/bubna.png
   - assets/pika1.png
   - assets/chirva1.png
   - assets/trefa1.png
   - assets/bubna1.png





#   - assets/card6.png
#   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
